First pass refactoring scrapers into separate modules
Cockatrice/Magic-Spoiler pull request #98
Opened 2017-07-04 22:50 UTC by leematos

This _could_ close #95. It needs a ton more work to really untangle to make sure the modules don't have weird cross dependencies but as a first pass it makes things a little bit more organized 🎉 I ran it locally and didn't hit any errors so I think it's safe to merge.

2017-07-04 23:04 UTC, leematos commented on main.py
> +                'https://api.scryfall_scraper.com/cards/search?q=++e:' + setinfo['setname'].lower())
This needs to get fixed.

2017-07-05 01:08 UTC, dev-id requested changes
Let's remove all unneeded imports

2017-07-05 01:56 UTC, tooomm commented
Can you explain a bit more what you did so far, please @leematos ?

If I checked correctly you basically just split up
`spoiler.py` --> in separate `*_scrapers.py` modules for each source (mtgs, scryfall, mythic and wizards)
as of now?

Because of all that format and space changes I might got lost on the way. :D

2017-07-05 03:16 UTC, dev-id approved these changes

2017-07-05 14:57 UTC, leematos commented
@tooomm Yep, for now I just separated them out into separate files (modules) so we can start to work to make them self-contained and make sure the flow of the program is a little bit clearer. A module should "do one thing" (which can turn into a semantic nightmare) but it seems to me that `spoilers.py` was defining a couple of different scrapers which is why I split them up here. 

The next steps after this would be:

1. Make sure each module has no weird cross dependencies.
1. Making sure each modules state is properly isolated and that modules pass consistent values out.
1. Writing tests for modules to make sure that when we make changes, that we get the expected result on the other side. :)

2017-07-05 16:57 UTC, tritoch commented
Can you see about matching the previous spacing conventions?

2017-07-05 16:59 UTC, leematos commented
I was actually worried about that @tritoch. I ran it though a PEP8 linter and just YOLO'd it since we should be following PEP8 anyway https://www.python.org/dev/peps/pep-0008/

2017-07-05 17:05 UTC, tritoch commented
Look at this guy, using style guides.

2017-07-05 17:24 UTC, tooomm commented
put that into contributing? (if that's what we like)

2017-07-06 00:53 UTC, leematos commented
I just squashed those fix import commits to clean up the history. This one's ready to merge! <3

2017-07-06 01:44 UTC, merged